method = 'copy'
plugin_dirs = [
    '/home/torgeir/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/torgeir/Dropbox/Music/Plugins/vst/linux',
]
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-7.1-288-g4364ff8d5c0 ( TkG Staging Esync Fsync )'
yabridge_host_hash = -8582222648145641155
