method = 'copy'
plugin_dirs = [
    '/home/torgeir/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/torgeir/Dropbox/Music/Plugins/vst/linux',
]
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-6.21.r0.g63c3baa9 ( TkG Staging Esync Fsync )'
yabridge_host_hash = -4651494022168063147
