window:
  opacity: 0.97
font:
  size: 18
  normal:
    family: IosevkaTermCurlySlab Nerd Font
    style: Regular

# https://github.com/alacritty/alacritty/issues/62#issuecomment-347552058
# \x1b is escape in hex
# debug what alacritty receives with
#  alacritty --print-events | grep Key
key_bindings:
  - { key: Tab, mods: Control,       chars: "\x1b[27;5;9~" } # make work with tmux binding C-Tab
  - { key: Tab, mods: Shift|Control, chars: "\x1b[27;6;9~" } # make work with tmux binding C-Shift-Tab

  - { key: Left,  mods: Alt|Super, chars: "\x1b[1;11D" } # make work with tmux user-keys[0] binding
  - { key: Down,  mods: Alt|Super, chars: "\x1b[1;11B" } # make work with tmux user-keys[1] binding
  - { key: Up,    mods: Alt|Super, chars: "\x1b[1;11A" } # make work with tmux user-keys[2] binding
  - { key: Right, mods: Alt|Super, chars: "\x1b[1;11C" } # make work with tmux user-keys[3] binding

  - { key: B, mods: Alt, chars: "\x1bb" } # fix m-b, backward word
  - { key: D, mods: Alt, chars: "\x1bd" } # fix m-d, delete word
  - { key: F, mods: Alt, chars: "\x1bf" } # fix m-f, forward word
  - { key: L, mods: Alt, chars: "\x1bl" } # fix m-l, lowercase word
  - { key: P, mods: Alt, chars: "\x1bp" } # fix m-p, prev
  - { key: N, mods: Alt, chars: "\x1bn" } # fix m-n, next
  - { key: T, mods: Alt, chars: "\x1bt" } # fix m-t, transpose word
  - { key: U, mods: Alt, chars: "\x1bu" } # fix m-u, uppercase word

  - { key: Period, mods: Alt|Shift, chars: "\x1b>" } # m->
  - { key: Comma, mods: Alt, chars: "\x1b<" } # m-<

# https://github.com/catppuccin/alacritty/blob/main/catppuccin-mocha.yml
colors:
  primary:
    background: "#1E1E2E" # base
    foreground: "#CDD6F4" # text
    # Bright and dim foreground colors
    dim_foreground: "#CDD6F4" # text
    bright_foreground: "#CDD6F4" # text
  # Cursor colors
  cursor:
    text: "#1E1E2E" # base
    cursor: "#F5E0DC" # rosewater
  vi_mode_cursor:
    text: "#1E1E2E" # base
    cursor: "#B4BEFE" # lavender
  # Search colors
  search:
    matches:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
    focused_match:
      foreground: "#1E1E2E" # base
      background: "#A6E3A1" # green
    footer_bar:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
  # Keyboard regex hints
  hints:
    start:
      foreground: "#1E1E2E" # base
      background: "#F9E2AF" # yellow
    end:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
  # Selection colors
  selection:
    text: "#1E1E2E" # base
    background: "#F5E0DC" # rosewater
  # Normal colors
  normal:
    black: "#45475A" # surface1
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#BAC2DE" # subtext1
  # Bright colors
  bright:
    black: "#585B70" # surface2
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#A6ADC8" # subtext0
  # Dim colors
  dim:
    black: "#45475A" # surface1
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#BAC2DE" # subtext1
  indexed_colors:
    - { index: 16, color: "#FAB387" }
    - { index: 17, color: "#F5E0DC" }
